### ISSUE TITLE
device_map: bogus sama53d entry ?

### ISSUE THREAD

**Issue by alexandrebelloni** [kernelci/lava-ci#52]
The following entry in device_map.py seems bogus, is it actually used?

```
sama53d = {'device_type': 'sama53d',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
           'kernel_defconfig_blacklist': [],
           'defconfig_blacklist': ['arm-at91_dt_defconfig',
                                   'arm-at91sam9260_9g20_defconfig',
                                   'arm-at91sam9g45_defconfig',
                                   'arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False}

```

**Comment by MiloCasagrande** [comment]
Looking through the source code, it looks like the "sama53d" entry is referenced in at least two places.
That said I'm not sure it is actually used in kernelci or if the name itself is misspelled (somewhere else in the code I see a "sama5d3").

Maybe @khilman can take a better look.

**Comment by khilman** [comment]
Looks used to me, including in lab-freeelectrons: ;https://kernelci.org/boot/at91-sama5d3_xplained/

Admittedly though, I'm not very familiar with the details of this file, so @alexandrebelloni: could you be more specific about why this is bogus or unused?

**Comment by alexandrebelloni** [comment]
Ok, I see it now. I suggest renaming sama53d in sama5d3_xplained if that is ok for everybody.

**Comment by QSchulz** [comment]
@alexandrebelloni Hum yes but no. The name used in LAVA has to remain `sama53d` because it is how the SAMA5D3 Xplained configuration file is named in LAVA (https://github.com/Linaro/lava-dispatcher/blob/master/lava_dispatcher/default-config/lava-dispatcher/device-types/sama53d.conf).
Renaming the device type used in LAVA would require all labs to remove the existing `sama53d` device type and replace it with `sama5d3_xplained` (we cannot rename the device type since the device type name is the primary key of this table in the database, thus this implies all labs losing their job results for this board).

The name used in LAVA is the `device_type` field in the board dictionary (lib/device_map.py) and the key in the `device_map` in lava-report.py.

However, you could change the internal variable (and that's the only acceptable and painless solution IMHO):

```
--- a/lib/device_map.py
+++ b/lib/device_map.py
@@ -495,7 +495,7 @@ highbank = {'device_type': 'highbank',
             'lpae': False,
             'fastboot': True}

-sama53d = {'device_type': 'sama53d',
+sama5d3_xplained = {'device_type': 'sama53d',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
@@ -1273,7 +1273,7 @@ device_map = {'bcm2835-rpi-b-plus.dtb': [bcm2835_rpi_b_plus],
               'qcom-apq8084-ifc6540.dtb': [ifc6540],
               'qcom-apq8064-ifc6410.dtb': [ifc6410],
               'highbank.dtb': [highbank],
-              'at91-sama5d3_xplained.dtb': [sama53d],
+              'at91-sama5d3_xplained.dtb': [sama5d3_xplained],
               'tegra124-jetson-tk1.dtb': [jetson_tk1],
               'tegra124-nyan-big.dtb': [tegra124_nyan_big],
               'zynq-parallella.dtb': [parallella],
```
