### ISSUE TITLE
lava-report.py doesn't fail when getting a 403 error from the API

### ISSUE THREAD

**Issue by MiloCasagrande** [kernelci/lava-ci#75]
When sending data via the backend API (uploading boot artifacts), if the backend sends a 403 error code (meaning the authorization token is not authorized), lava-report.py doesn't treat that error code correctly and considers it as a valid one.

It should probably exit in a way that we can mark the job as failed, since it is not able to upload anything.

**Comment by gctucker** [comment]
I guess this isn't an issue with LAVA v2 anymore as the boot results and logs are created in the backend via the callback handler.  Is there any issue with sending kernel builds to the storage (with `build.py` I maybe)?

**Comment by MiloCasagrande** [comment]
I have no idea anymore.

The backend can still respond with 403 even with the callbacks, so if whatever is sending that request is handling the errors code correctly, that is fine.

`build.py` could be affected.

**Comment by mattface** [comment]
Close it. build.py has retry support, but if it fails all attempts you just
don't get a build result.

lava-report.py was a bigger problem because if it gets a 403 then all the
boot jobs from that lab for that arch will be lost. Callbacks are per job
so I'd just let 1 job not be reported and not worry about it
